vérification fichier de cache vide ou xml erronné
Cadoles/BeSimpleSoap pull request #2
Opened 2019-09-23 16:46 UTC by scriptted

2019-09-23 19:33 UTC, bohwaz requested changes
Tu pourrais séparer les corrections de style de code (PHPCS ?) des modifications actuelles ? Merci.

2019-09-24 12:41 UTC, Bornholm requested changes

2019-09-24 12:41 UTC, Bornholm commented on src/BeSimple/SoapClient/WsdlDownloader.php
> +                    throw new \Exception('Une erreur a été détecté dans le fichier WSDL. Le fichier a été supprimé du cache.');
Peut être mettre le message d'erreur en anglais ? :)

2019-09-24 12:57 UTC, Bornholm approved these changes

2019-09-24 12:57 UTC, bohwaz approved these changes

2019-09-24 13:19 UTC, merged